-- RepSaga Custom Email Templates for Supabase
--
-- HOW TO APPLY:
-- 1. Go to Supabase Dashboard > Authentication > Email Templates
-- 2. Replace the default template content for each template type
-- 3. Copy the HTML from each section below into the corresponding template
--
-- These templates match RepSaga's dark+green brand identity.
-- Variables: {{ .ConfirmationURL }}, {{ .Email }}, {{ .Token }}

-- ============================================================
-- TEMPLATE: Confirm signup
-- Subject: Confirm your RepSaga account
-- ============================================================
-- Copy the HTML below into the "Confirm signup" template body:
--
-- <html>
-- <body style="margin:0;padding:0;background-color:#0F0F1A;font-family:'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
--   <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#0F0F1A;padding:40px 0;">
--     <tr>
--       <td align="center">
--         <table width="480" cellpadding="0" cellspacing="0" style="background-color:#1A1A2E;border-radius:16px;padding:40px;max-width:480px;">
--           <tr>
--             <td align="center" style="padding-bottom:24px;">
--               <span style="font-size:36px;font-weight:800;color:#00E676;letter-spacing:-0.5px;">RepSaga</span>
--             </td>
--           </tr>
--           <tr>
--             <td align="center" style="padding-bottom:16px;">
--               <span style="font-size:24px;font-weight:700;color:#FFFFFF;">Confirm your email</span>
--             </td>
--           </tr>
--           <tr>
--             <td align="center" style="padding-bottom:32px;">
--               <span style="font-size:16px;color:#B0B0C0;line-height:1.5;">
--                 You're one step away from tracking every rep.<br/>
--                 Tap the button below to verify your email and get started.
--               </span>
--             </td>
--           </tr>
--           <tr>
--             <td align="center" style="padding-bottom:32px;">
--               <a href="{{ .ConfirmationURL }}"
--                  style="display:inline-block;background-color:#00E676;color:#000000;font-size:16px;font-weight:700;
--                         padding:16px 40px;border-radius:12px;text-decoration:none;letter-spacing:1.2px;">
--                 CONFIRM EMAIL
--               </a>
--             </td>
--           </tr>
--           <tr>
--             <td align="center" style="padding-bottom:16px;">
--               <span style="font-size:13px;color:#666680;">
--                 If you didn't create a RepSaga account, you can safely ignore this email.
--               </span>
--             </td>
--           </tr>
--           <tr>
--             <td align="center">
--               <span style="font-size:12px;color:#444460;">
--                 This link expires in 24 hours.
--               </span>
--             </td>
--           </tr>
--         </table>
--       </td>
--     </tr>
--   </table>
-- </body>
-- </html>

-- ============================================================
-- TEMPLATE: Reset password
-- Subject: Reset your RepSaga password
-- ============================================================
-- Copy the HTML below into the "Reset password" template body:
--
-- <html>
-- <body style="margin:0;padding:0;background-color:#0F0F1A;font-family:'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
--   <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#0F0F1A;padding:40px 0;">
--     <tr>
--       <td align="center">
--         <table width="480" cellpadding="0" cellspacing="0" style="background-color:#1A1A2E;border-radius:16px;padding:40px;max-width:480px;">
--           <tr>
--             <td align="center" style="padding-bottom:24px;">
--               <span style="font-size:36px;font-weight:800;color:#00E676;letter-spacing:-0.5px;">RepSaga</span>
--             </td>
--           </tr>
--           <tr>
--             <td align="center" style="padding-bottom:16px;">
--               <span style="font-size:24px;font-weight:700;color:#FFFFFF;">Reset your password</span>
--             </td>
--           </tr>
--           <tr>
--             <td align="center" style="padding-bottom:32px;">
--               <span style="font-size:16px;color:#B0B0C0;line-height:1.5;">
--                 We received a request to reset your password.<br/>
--                 Tap the button below to choose a new one.
--               </span>
--             </td>
--           </tr>
--           <tr>
--             <td align="center" style="padding-bottom:32px;">
--               <a href="{{ .ConfirmationURL }}"
--                  style="display:inline-block;background-color:#00E676;color:#000000;font-size:16px;font-weight:700;
--                         padding:16px 40px;border-radius:12px;text-decoration:none;letter-spacing:1.2px;">
--                 RESET PASSWORD
--               </a>
--             </td>
--           </tr>
--           <tr>
--             <td align="center" style="padding-bottom:16px;">
--               <span style="font-size:13px;color:#666680;">
--                 If you didn't request a password reset, you can safely ignore this email.<br/>
--                 Your password will remain unchanged.
--               </span>
--             </td>
--           </tr>
--           <tr>
--             <td align="center">
--               <span style="font-size:12px;color:#444460;">
--                 This link expires in 1 hour.
--               </span>
--             </td>
--           </tr>
--         </table>
--       </td>
--     </tr>
--   </table>
-- </body>
-- </html>

-- ============================================================
-- TEMPLATE: Magic link
-- Subject: Your RepSaga login link
-- ============================================================
-- Copy the HTML below into the "Magic link" template body:
--
-- <html>
-- <body style="margin:0;padding:0;background-color:#0F0F1A;font-family:'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
--   <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#0F0F1A;padding:40px 0;">
--     <tr>
--       <td align="center">
--         <table width="480" cellpadding="0" cellspacing="0" style="background-color:#1A1A2E;border-radius:16px;padding:40px;max-width:480px;">
--           <tr>
--             <td align="center" style="padding-bottom:24px;">
--               <span style="font-size:36px;font-weight:800;color:#00E676;letter-spacing:-0.5px;">RepSaga</span>
--             </td>
--           </tr>
--           <tr>
--             <td align="center" style="padding-bottom:16px;">
--               <span style="font-size:24px;font-weight:700;color:#FFFFFF;">Your login link</span>
--             </td>
--           </tr>
--           <tr>
--             <td align="center" style="padding-bottom:32px;">
--               <span style="font-size:16px;color:#B0B0C0;line-height:1.5;">
--                 Tap the button below to log in to RepSaga.<br/>
--                 No password needed.
--               </span>
--             </td>
--           </tr>
--           <tr>
--             <td align="center" style="padding-bottom:32px;">
--               <a href="{{ .ConfirmationURL }}"
--                  style="display:inline-block;background-color:#00E676;color:#000000;font-size:16px;font-weight:700;
--                         padding:16px 40px;border-radius:12px;text-decoration:none;letter-spacing:1.2px;">
--                 LOG IN
--               </a>
--             </td>
--           </tr>
--           <tr>
--             <td align="center" style="padding-bottom:16px;">
--               <span style="font-size:13px;color:#666680;">
--                 If you didn't request this link, you can safely ignore this email.
--               </span>
--             </td>
--           </tr>
--           <tr>
--             <td align="center">
--               <span style="font-size:12px;color:#444460;">
--                 This link expires in 1 hour.
--               </span>
--             </td>
--           </tr>
--         </table>
--       </td>
--     </tr>
--   </table>
-- </body>
-- </html>
