import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:repsaga/features/rpg/domain/xp_calculator.dart';

/// Loads the JSON fixtures generated by
/// `test/fixtures/generate_rpg_fixtures.py`. The fixture is the
/// **single source of truth** for Dart-vs-Python parity. If a constant
/// changes here without regenerating the fixture, this test fails — that
/// is intentional.
Map<String, dynamic> _loadFixtures() {
  final file = File('test/fixtures/rpg_xp_fixtures.json');
  if (!file.existsSync()) {
    throw StateError(
      'rpg_xp_fixtures.json missing — run '
      '`python test/fixtures/generate_rpg_fixtures.py` first.',
    );
  }
  return json.decode(file.readAsStringSync()) as Map<String, dynamic>;
}

/// Tolerance for double parity. Volume_load^0.65 with strength_mult and
/// novelty introduces some float rounding; 1e-9 absolute is far tighter
/// than anything user-observable but loose enough that x86_64 vs ARM
/// double-rounding doesn't false-fail.
const double _eps = 1e-9;

void main() {
  late final Map<String, dynamic> fixtures;

  setUpAll(() {
    fixtures = _loadFixtures();
  });

  group('Constants parity with Python sim', () {
    test('volume_exponent == 0.65', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      expect(XpCalculator.volumeExponent, meta['volume_exponent']);
      expect(XpCalculator.volumeExponent, 0.65);
    });

    test('novelty_denominator == 15', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      expect(XpCalculator.noveltyDenominator, meta['novelty_denominator']);
    });

    test('weekly_cap_sets == 20 with 0.5 over-cap multiplier', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      expect(XpCalculator.weeklyCapSets, meta['weekly_cap_sets']);
      expect(XpCalculator.overCapMultiplier, meta['over_cap_multiplier']);
    });

    test('strength_mult_floor == 0.40', () {
      final meta = fixtures['meta'] as Map<String, dynamic>;
      expect(XpCalculator.strengthMultFloor, meta['strength_mult_floor']);
    });
  });

  group('intensityForReps — table parity', () {
    test('every reps boundary returns the spec multiplier', () {
      final cases = fixtures['intensity_lookup'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final reps = c['reps'] as int;
        final expected = (c['intensity_mult'] as num).toDouble();
        expect(
          XpCalculator.intensityForReps(reps),
          closeTo(expected, _eps),
          reason: 'reps=$reps should yield $expected',
        );
      }
    });

    test('reps below 1 fall back to 1.0', () {
      expect(XpCalculator.intensityForReps(0), 1.0);
      expect(XpCalculator.intensityForReps(-5), 1.0);
    });

    test('reps boundary semantics: 4 reps lands in the >=3 row (1.25)', () {
      expect(XpCalculator.intensityForReps(4), 1.25);
    });

    test('reps boundary semantics: 8 reps lands in the >=8 row (1.00)', () {
      expect(XpCalculator.intensityForReps(8), 1.00);
    });

    test('reps boundary semantics: 13 reps lands in the >=12 row (0.95)', () {
      expect(XpCalculator.intensityForReps(13), 0.95);
    });

    test('reps 25+ saturate at 0.80', () {
      expect(XpCalculator.intensityForReps(25), 0.80);
      expect(XpCalculator.intensityForReps(100), 0.80);
    });
  });

  group('volumeLoad + baseXp — parity', () {
    test('every fixture case matches', () {
      final cases = fixtures['volume_load'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final w = (c['weight_kg'] as num).toDouble();
        final r = c['reps'] as int;
        final vlExpected = (c['volume_load'] as num).toDouble();
        final baseExpected = (c['base_xp'] as num).toDouble();
        final vl = XpCalculator.volumeLoad(weightKg: w, reps: r);
        expect(
          vl,
          closeTo(vlExpected, _eps),
          reason: 'volume_load(w=$w, r=$r)',
        );
        expect(
          XpCalculator.baseXp(vl),
          closeTo(baseExpected, _eps),
          reason: 'base_xp(vl=$vl)',
        );
      }
    });

    test('volume_load floor is 1.0', () {
      expect(XpCalculator.volumeLoad(weightKg: 0, reps: 8), 1.0);
      expect(XpCalculator.volumeLoad(weightKg: 0.1, reps: 1), 1.0);
    });

    test('reps < 1 returns the floor', () {
      expect(XpCalculator.volumeLoad(weightKg: 100, reps: 0), 1.0);
      expect(XpCalculator.volumeLoad(weightKg: 100, reps: -1), 1.0);
    });
  });

  group('strengthMult — clamp + floor', () {
    test('every fixture case matches', () {
      final cases = fixtures['strength_mult'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final w = (c['weight_kg'] as num).toDouble();
        final p = (c['peak_load'] as num).toDouble();
        final expected = (c['strength_mult'] as num).toDouble();
        expect(
          XpCalculator.strengthMult(weightKg: w, peakLoad: p),
          closeTo(expected, _eps),
          reason: 'strengthMult(weight=$w, peak=$p)',
        );
      }
    });

    test('weight at peak yields exactly 1.0', () {
      expect(XpCalculator.strengthMult(weightKg: 100, peakLoad: 100), 1.0);
    });

    test('weight above peak clamps to 1.0', () {
      expect(XpCalculator.strengthMult(weightKg: 110, peakLoad: 100), 1.0);
    });

    test('weight below floor floors to 0.4', () {
      expect(XpCalculator.strengthMult(weightKg: 30, peakLoad: 100), 0.4);
      expect(XpCalculator.strengthMult(weightKg: 1, peakLoad: 100), 0.4);
    });

    test('peak == 0 returns 1.0 (no prior peak — divide-by-zero guard)', () {
      expect(XpCalculator.strengthMult(weightKg: 50, peakLoad: 0), 1.0);
      expect(XpCalculator.strengthMult(weightKg: 0, peakLoad: 0), 1.0);
    });
  });

  group('noveltyMult — exp decay', () {
    test('every fixture case matches', () {
      final cases = fixtures['novelty_mult'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final sv = (c['session_volume_for_body_part'] as num).toDouble();
        final expected = (c['novelty_mult'] as num).toDouble();
        expect(
          XpCalculator.noveltyMult(sv),
          closeTo(expected, _eps),
          reason: 'noveltyMult(sv=$sv)',
        );
      }
    });

    test('zero session volume returns 1.0', () {
      expect(XpCalculator.noveltyMult(0), 1.0);
    });

    test('session volume of 15 returns ~0.368 (e^-1)', () {
      expect(XpCalculator.noveltyMult(15), closeTo(0.367879441, 1e-6));
    });

    test('negative input is clamped to 1.0 (defensive)', () {
      expect(XpCalculator.noveltyMult(-5), 1.0);
    });
  });

  group('capMult — weekly cap', () {
    test('every fixture case matches', () {
      final cases = fixtures['cap_mult'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final wv = (c['weekly_volume_for_body_part'] as num).toDouble();
        final expected = (c['cap_mult'] as num).toDouble();
        expect(
          XpCalculator.capMult(wv),
          expected,
          reason: 'capMult(weeklyVolume=$wv)',
        );
      }
    });

    test('exactly 20 sets triggers the cap (>= boundary)', () {
      expect(XpCalculator.capMult(20.0), 0.5);
      // Just below the boundary stays at 1.0
      expect(XpCalculator.capMult(19.999), 1.0);
    });
  });

  group('computeSetXp — end-to-end parity', () {
    test('every set_xp fixture case matches all components within $_eps', () {
      final cases = fixtures['set_xp_examples'] as List<dynamic>;
      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final inputs = c['inputs'] as Map<String, dynamic>;
        final components = c['components'] as Map<String, dynamic>;

        final result = XpCalculator.computeSetXp(
          weightKg: (inputs['weight_kg'] as num).toDouble(),
          reps: inputs['reps'] as int,
          peakLoad: (inputs['peak_load'] as num).toDouble(),
          sessionVolumeForBodyPart:
              (inputs['session_volume_for_body_part'] as num).toDouble(),
          weeklyVolumeForBodyPart:
              (inputs['weekly_volume_for_body_part'] as num).toDouble(),
        );

        final name = c['name'] as String;
        expect(
          result.volumeLoad,
          closeTo((components['volume_load'] as num).toDouble(), _eps),
          reason: '[$name] volume_load',
        );
        expect(
          result.baseXp,
          closeTo((components['base_xp'] as num).toDouble(), _eps),
          reason: '[$name] base_xp',
        );
        expect(
          result.intensityMult,
          closeTo((components['intensity_mult'] as num).toDouble(), _eps),
          reason: '[$name] intensity_mult',
        );
        expect(
          result.strengthMult,
          closeTo((components['strength_mult'] as num).toDouble(), _eps),
          reason: '[$name] strength_mult',
        );
        expect(
          result.noveltyMult,
          closeTo((components['novelty_mult'] as num).toDouble(), _eps),
          reason: '[$name] novelty_mult',
        );
        expect(
          result.capMult,
          closeTo((components['cap_mult'] as num).toDouble(), _eps),
          reason: '[$name] cap_mult',
        );
        expect(
          result.setXp,
          closeTo((c['set_xp'] as num).toDouble(), _eps),
          reason: '[$name] total set_xp',
        );
      }
    });

    test(
      'peak advances the set still earns 1.0× (since we floor peak to weight)',
      () {
        // When weight > recorded peak, the calculator returns 1.0 (the
        // record_set_xp RPC is responsible for advancing the peak BEFORE
        // computing strength_mult; we test that the calculator is consistent
        // with peak == weight). This mirrors the SQL contract.
        final r = XpCalculator.computeSetXp(
          weightKg: 110,
          reps: 5,
          peakLoad: 100, // stale peak — RPC would advance to 110 first
          sessionVolumeForBodyPart: 0,
          weeklyVolumeForBodyPart: 0,
        );
        // 110/100 = 1.1, clamped to 1.0
        expect(r.strengthMult, 1.0);
      },
    );

    test(
      'toJson() produces the breakdown shape stored on xp_events.payload',
      () {
        final r = XpCalculator.computeSetXp(
          weightKg: 100,
          reps: 5,
          peakLoad: 100,
          sessionVolumeForBodyPart: 0,
          weeklyVolumeForBodyPart: 0,
        );
        final json = r.toJson();
        expect(json.keys.toSet(), {
          'volume_load',
          'base_xp',
          'intensity_mult',
          'strength_mult',
          'novelty_mult',
          'cap_mult',
          'set_xp',
        });
        expect(json['set_xp'], r.setXp);
      },
    );
  });

  group('Boundary + edge cases', () {
    test(
      'zero weight + zero reps → set_xp = 1.0^0.65 × 1 × 1 × 1 × 1 = 1.0',
      () {
        final r = XpCalculator.computeSetXp(
          weightKg: 0,
          reps: 0,
          peakLoad: 0,
          sessionVolumeForBodyPart: 0,
          weeklyVolumeForBodyPart: 0,
        );
        expect(r.volumeLoad, 1.0);
        expect(r.baseXp, 1.0);
        expect(r.setXp, 1.0); // 1 × 1 × 1 × 1 × 1
      },
    );

    test('massive weight does not produce infinity or NaN', () {
      final r = XpCalculator.computeSetXp(
        weightKg: 9999,
        reps: 20,
        peakLoad: 9999,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 0,
      );
      expect(r.setXp.isFinite, isTrue);
      expect(r.setXp, greaterThan(0));
    });

    test('past the weekly cap with high session volume compounds', () {
      final r = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 5,
        peakLoad: 100,
        sessionVolumeForBodyPart: 30, // deep into novelty decay
        weeklyVolumeForBodyPart: 30, // past cap
      );
      // novelty = exp(-2) ≈ 0.1353, cap = 0.5 → set_xp << base
      final base = XpCalculator.baseXp(
        XpCalculator.volumeLoad(weightKg: 100, reps: 5),
      );
      expect(r.setXp, lessThan(base * 0.10));
    });

    test('all multipliers at unity → set_xp == base_xp × intensity', () {
      final r = XpCalculator.computeSetXp(
        weightKg: 100,
        reps: 8, // intensity 1.0
        peakLoad: 100,
        sessionVolumeForBodyPart: 0,
        weeklyVolumeForBodyPart: 0,
      );
      expect(r.intensityMult, 1.0);
      expect(r.strengthMult, 1.0);
      expect(r.noveltyMult, 1.0);
      expect(r.capMult, 1.0);
      expect(r.setXp, closeTo(r.baseXp, _eps));
    });
  });
}
